//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo se generÃ³ a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaciÃ³n.
//     Los cambios manuales en este archivo se sobrescribirÃ¡n si se regenera el cÃ³digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadParcial2Krba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Canal()
        {
            this.Progama = new HashSet<Progama>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string frecuencia { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progama> Progama { get; set; }
    }
}

