//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadParcial2Krba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progama
    {
        public int id { get; set; }
        public int idCanal { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public int duracion { get; set; }
        public string productor { get; set; }
        public System.DateTime fechaEstreno { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
        public int idCategoriaPrograma { get; set; }
    
        public virtual Canal Canal { get; set; }
        public virtual CategoriaPrograma CategoriaPrograma { get; set; }
    }
}
